version: "3.9"

services:
    nginx:
        build:
            context: .
        image: nginx:latest
        restart: always
        networks:
            app_net:
                ipv4_address: 172.18.18.11
        ports:
            - "8088:80"
        volumes:
            - .:/var/www/
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        image: php:8.2-fpm
        build:
            context: .
            dockerfile: ./docker/dockerfile
        restart: always
        volumes:
            - .:/var/www/
            - ./docker/php.ini:/usr/local/etc/php/php.ini
        networks:
            app_net:
                ipv4_address: 172.18.18.21
    redis:
        image: redis/redis-stack:latest
        restart: always
        ports:
            - "16379:6379"
        networks:
            app_net:
                ipv4_address: 172.18.18.81
    mysql:
        image: mysql/mysql-server:latest
        volumes:
            - ./docker/mysql-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'fuck123sql'
            MYSQL_ROOT_HOST: '0.0.0.0'
        ports:
            - "13306:3306"
        networks:
            app_net:
                ipv4_address: 172.18.18.188

networks:
    app_net:
        ipam:
            driver: default
            config:
                -   subnet: 172.18.18.0/24
