FROM php:8.2-fpm

RUN apt-get update -y

RUN apt-get install -y libpq-dev libzip-dev zip zlib1g-dev libpng-dev && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install zip \
    && docker-php-ext-install pdo pdo_mysql \
    && docker-php-ext-install gd \
    && docker-php-ext-enable gd.so

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

RUN pecl install redis \ && docker-php-ext-enable redis.so

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
